[chains]

[chains.neutron]
chain_id = "neutron-1"
name = "neutron"
rpc  = "https://rpc-voidara.neutron-1.neutron.org"
grpc = "https://grpc-kralum.neutron-1.neutron.org:80"
prefix    = "neutron"
gas_price = "0.0053"
gas_denom = "untrn"
coin_type = "118"

[chains.juno]
chain_id = "juno-1"
name = "juno"
rpc  = "https://juno-rpc.polkachu.com:443"
grpc = "https://juno-grpc.polkachu.com:12690"
prefix    = "juno"
gas_price = "0.075"
gas_denom = "ujuno"
coin_type = "118"

[chains.terra]
chain_id = "phoenix-1"
name = "terra"
rpc  = "https://terra-rpc.polkachu.com:443"
grpc = "https://terra-grpc.polkachu.com:11790"
prefix    = "terra"
gas_price = "0.015"
gas_denom = "uluna"
coin_type = "330"

[chains.osmosis]
chain_id = "osmosis-1"
name = "osmosis"
rpc  = "https://osmosis-rpc.polkachu.com:443"
grpc = "https://osmosis-grpc.polkachu.com:11790"
prefix    = "osmo"
gas_price = "0.015"
gas_denom = "uosmo"
coin_type = "118"