[contracts]

[contracts.code_ids.neutron]
# Registry is not used and only needed on neutron
valence_program_registry         = 3234
valence_authorization            = 3225
valence_processor                = 3226
valence_base_account             = 3227
valence_forwarder_library        = 3228
valence_splitter_library         = 3229
valence_reverse_splitter_library = 3230
valence_drop_liquid_staker       = 3231
valence_astroport_lper           = 3232
valence_astroport_withdrawer     = 3233
valence_drop_liquid_unstaker     = 3255
