[contracts]

[contracts.code_ids.neutron]
# Registry is not used and only needed on neutron
polytone_proxy                       = 231
valence_astroport_lper               = 3316
valence_astroport_withdrawer         = 3317
valence_authorization                = 3318
valence_base_account                 = 3319
valence_drop_liquid_staker           = 3320
valence_drop_liquid_unstaker         = 3321
valence_forwarder_library            = 3322
valence_generic_ibc_transfer_library = 3323
valence_neutron_ibc_transfer_library = 3324
valence_processor                    = 3325
valence_program_registry             = 3326
valence_reverse_splitter_library     = 3327
valence_splitter_library             = 3328

[contracts.code_ids.juno]
polytone_proxy                       = 3321
valence_astroport_lper               = 4801
valence_astroport_withdrawer         = 4802
valence_base_account                 = 4803
valence_drop_liquid_staker           = 4804
valence_drop_liquid_unstaker         = 4805
valence_forwarder_library            = 4806
valence_generic_ibc_transfer_library = 4810
valence_processor                    = 4807
valence_reverse_splitter_library     = 4808
valence_splitter_library             = 4809

[contracts.code_ids.terra]
polytone_proxy                       = 2372
valence_astroport_lper               = 3571
valence_astroport_withdrawer         = 3572
valence_base_account                 = 3573
valence_drop_liquid_staker           = 3574
valence_drop_liquid_unstaker         = 3575
valence_forwarder_library            = 3576
valence_generic_ibc_transfer_library = 3580
valence_processor                    = 3577
valence_reverse_splitter_library     = 3578
valence_splitter_library             = 3579
