[contracts]

[contracts.code_ids.neutron]
# Registry is not used and only needed on neutron
polytone_proxy                       = 231
valence_astroport_lper               = 3297
valence_astroport_withdrawer         = 3298
valence_authorization                = 3299
valence_base_account                 = 3300
valence_forwarder_library            = 3301
valence_generic_ibc_transfer_library = 3306
valence_neutron_ibc_transfer_library = 3307
valence_processor                    = 3302
valence_program_registry             = 3303
valence_reverse_splitter_library     = 3304
valence_splitter_library             = 3305

[contracts.code_ids.juno]
polytone_proxy                       = 3321
valence_processor                    = 4780
valence_base_account                 = 4781
valence_forwarder_library            = 4782
valence_splitter_library             = 4783
valence_reverse_splitter_library     = 4784
valence_generic_ibc_transfer_library = 4785

[contracts.code_ids.terra]
polytone_proxy                       = 2372
valence_processor                    = 3552
valence_base_account                 = 3554
valence_forwarder_library            = 3555
valence_splitter_library             = 3556
valence_reverse_splitter_library     = 3557
valence_generic_ibc_transfer_library = 3558
valence_astroport_lper               = 3560
valence_astroport_withdrawer         = 3561